---
title: "Cleaning T2 data"
output: html_notebook
---


Since the PSID went to a biennial format after 1997, the file *LaborFile.csv* does not have data for 1998,2000, and so on. A supplementary set of questions is asked about the family members from the previous year. These are sometimes called the "T2" supplement, which the chunk of code below cleans into a panel dataset for those missing years. These data were collected from the "Individual Data Index" from the PSID's data center tool, so they are linked to individuals already. The code below renames the variables and reshapes them into a panel. The reporting of earnings in these years is slightly different from the main questions, so we keep only observations that are reported in annual terms (the large majority). There is also an abnormally large increase in the number of individuals who report zero hours but positive earnings from 2001 and on. We have to correct for this using the T2 variables from the main interview file.

```{r}
Dt2 <- read.csv("../../../data-main/labor-market/T2.csv") %>% 
  mutate(MID = ER30001*1000 + ER30002,FID = MID) %>%
  rename(earn97 = ER33536A,earn99 = ER33627A,earn01 = ER33727A) %>%
  rename(earn97u = ER33536B,earn99u = ER33627B,earn01u = ER33727B) %>%
  rename(wage97 = ER33537O,wage99 = ER33628O,wage01 = ER33728O) %>%
  rename(ww97 = ER33536C,ww99 = ER33627C,ww01 = ER33727C) %>%
  rename(hw97 = ER33536Q,hw99 = ER33627Q,hw01 = ER33727Q)
  
# let's just do these for now
D97 <- Dt2 %>% select(MID,FID,earn97,earn97u,wage97,ww97,hw97) %>%
  rename(earn=earn97,earnu=earn97u,wage=wage97,ww=ww97,hw=hw97) %>%
  mutate(year=1997)

D99 <- Dt2 %>% select(MID,FID,earn99,earn99u,wage99,ww99,hw99) %>%
  rename(earn=earn99,earnu=earn99u,wage=wage99,ww=ww99,hw=hw99) %>%
  mutate(year=1999)

D01 <- Dt2 %>% select(MID,FID,earn01,earn01u,wage01,ww01,hw01) %>%
  rename(earn=earn01,earnu=earn01u,wage=wage01,ww=ww01,hw=hw01) %>%
  mutate(year=2001)

# --- Now, read in the T-2 in 2001 variables from the family file
Dt2 <- read.csv("../../../data-main/labor-market/T2_supp.csv") %>% 
  rename(intnum = ER21002,h_earn = ER23702F1,h_ww = ER23702D3,h_hw = ER23702E8) %>%
  rename(w_earn = ER23702L4, w_ww = ER23702J6, w_hw = ER23702L2) %>%
  mutate(year = 2003)

d01 <- read.csv("../../../data-main/identifiers/identifiers-panel.csv") %>% 
  filter(year==2003) %>% 
  mutate(X = NULL,MID = intnum68*1000 + pernum) %>%
  merge(Dt2) %>%
  mutate(year = 2001)


D01 <- merge(D01,d01)
Ih = D01$sn==1
D01[Ih,c("earn","hw","ww")] = D01[Ih,c("h_earn","h_hw","h_ww")]
Iw = D01$sn==2
D01[Iw,c("earn","hw","ww")] = D01[Iw,c("w_earn","w_hw","w_ww")]
D01 <- select(D01,c("MID","FID","year","earn","earnu","wage","hw","ww"))

T2 <- rbind(D97,D99,D01) %>%
  mutate(earn = na_if(na_if(na_if(na_if(earn,-9999999),-999999),99999999),9999999)) %>%
  #mutate(earn = case_when(earnu==1 ~ earn*hw*ww,earnu==2 ~ earn*365,earnu==3 ~ earn*ww, earnu==4 ~ earn*ww/2,earnu==5 ~ earn*12, earnu==6 ~ earn, TRUE ~ NA_real_)) %>%
  mutate(ww = na_if(ww,99),hw=na_if(hw,999)) %>%
  mutate(hrs = ww*hw) %>%
  #mutate(wage2 = case_when(earn>0 & hrs>0 ~ earn/hrs,TRUE ~ NA_real_),0) %>%
  mutate(wage = case_when(wage<=0 ~ NA_real_,wage==999 ~ NA_real_,TRUE ~ wage)) %>%
  mutate(wage = case_when(earn>0 & is.na(wage) ~ earn/hrs, TRUE ~ wage))

write.csv(T2,"../../../data-main/labor-market/T2clean.csv")

```